---
name: "weewx"

volumes:
  data:

services:
  weewx:
    image: felddy/weewx:5
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - type: bind
        source: ./data
        target: /data
