---
name: "weewx"

volumes:
  data:

services:
  weewx:
    image: felddy/weewx:5.0.2
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TIMEZONE=UTC
      - WEEWX_UID=weewx
      - WEEWX_GID=dialout
